spring.application.name=budget-app
#Lokalne wykorzystanie PostgreSQL, przez brak mo?liwo?ci u?ycia Dockera ko?cowo u?ycie bazy H2 in memory
#spring.datasource.url=jdbc:postgresql://localhost:5432/budget_db
#spring.datasource.username=postgres
#spring.datasource.password=admimimi5432
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:h2:mem:budgetapp;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.show-sql=true